---
title: "STAC51 Project"
output: 
  pdf_document: default
date: "2023-03-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(car)

set.seed(123456)

data = read.csv("Credit.csv")

split <- rbinom(nrow(data), 1, 0.5)

data_build <- data[split == 1, ]
data_valid <- data[split == 0, ]

remove(data)
```

# Model Building 

## Binomial Logistic
```{r}
#I took out some interactions that had to do with foreign_worker because it was returning NA. 
terms1 = "(property + housing + number_credits + job + people_liable + telephone + duration + credit_history + purpose + amount + savings + employment_duration + installment_rate + personal_status_sex + other_debtors + present_residence + age + other_installment_plans + status)^2 + foreign_worker*(property + housing + number_credits + job + people_liable + telephone + duration + credit_history + purpose + amount + savings + employment_duration + installment_rate + personal_status_sex)"

fit1 = glm(paste("credit_risk ~", terms1, sep = " "), family=binomial(link="logit"), data = data_build)
```


```{r}
#Please don't run this chunk. It takes awhile.
fit_simple <- glm(credit_risk ~ 1, family = "binomial", data=data_build)
step = suppressWarnings(step(fit1, direction="both", scope=list(upper=fit1, lower=fit_simple)))
```

#Binomial Logistic
```{r}
terms2 = paste(attr(terms(step), "term.labels"), collapse = "+")
fit2 = glm(paste("credit_risk ~", terms2, sep = " "), family = binomial(link="logit"), data=data_build)
summary(fit2)
```

## Binomial Probit
```{r}
fit3 = glm(paste("credit_risk ~", terms2, sep = " "), family = binomial(link="probit"), data=data_build)
summary(fit3)
```

## Significant Values Only. Alpha = 0.05
```{r}
#I took out the insignificant values from fit2. The AIC is actually lower, so this appears to be less efficient.
#This makes sense, since I just ran a stepwise(direction="both") on fit1. Therefore, fit2 should be optimal AIC-wise.

terms3 = "property + job + people_liable + amount + savings + employment_duration + personal_status_sex + other_installment_plans + status + property:job + property:people_liable + property:telephone + property:credit_history + property:amount + property:installment_rate + property:personal_status_sex + property:other_installment_plans + property:status + housing:number_credits + housing:job + housing:duration + housing:credit_history + housing:installment_rate + number_credits:job + number_credits:people_liable + number_credits:duration + number_credits:employment_duration + number_credits:installment_rate + number_credits:other_installment_plans + job:people_liable + job:duration + job:purpose + job:amount + job:present_residence + job:age + people_liable:duration + people_liable:amount + people_liable:other_installment_plans + telephone:credit_history + telephone:amount + telephone:savings + telephone:employment_duration + telephone:other_debtors + telephone:age + duration:amount + duration:savings + duration:installment_rate + duration:other_debtors + duration:present_residence + duration:age + duration:other_installment_plans + credit_history:installment_rate + credit_history:other_debtors + credit_history:present_residence + credit_history:other_installment_plans + purpose:savings + purpose:age + purpose:other_installment_plans + amount:savings + amount:installment_rate + amount:present_residence + amount:age + amount:other_installment_plans + savings:other_debtors + savings:present_residence + savings:age + savings:other_installment_plans + employment_duration:other_debtors + employment_duration:present_residence + employment_duration:other_installment_plans + employment_duration:status + installment_rate:personal_status_sex + installment_rate:present_residence + installment_rate:age + installment_rate:status + personal_status_sex:age + personal_status_sex:other_installment_plans + other_debtors:status + present_residence:age + present_residence:other_installment_plans + age:other_installment_plans + people_liable:other_debtors + property:other_debtors + job:status + savings:personal_status_sex"

fit4 = glm(paste("credit_risk ~", terms3, sep = " "), family = binomial(link="logit"), data=data_build)
summary(fit4)
```


# Diagnoses

```{r}
#The next step is to get rid of leverage and outliers. 
```